M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date tis  7 feb 2023 21:12:28
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-07T21:12:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.7774Y-2.2568
X6.0057Y-2.2568
T0
M30
